/* This sql statement exports all fields from within the person content type. Including a NTL specific field for inclusion in our directory.
*  The file generated by exporting this query is the basis for the person migration YML file: migrate_plus.migration.deims_csv_person.yml
*  The organization migration needs to run first (migrate_plus.migration.deims_nodes_organization.yml). The person migration will then resolve the link to an organization.
*/

SELECT
node.nid,
node.vid,
node.type,
node.`language`,
node.title,
node.uid,
node.`status`,
node.created,
node.`changed`,
node.`comment`,
node.promote,
node.sticky,
node.tnid,
node.translate,
field_data_field_person_department.field_person_department_value,
field_data_field_person_role.field_person_role_value,
field_data_field_person_specialty.field_person_specialty_value,
field_data_field_person_title.field_person_title_value,
field_data_field_person_image.field_person_image_fid,
field_data_field_person_image.field_person_image_alt,
field_data_field_person_image.field_person_image_width,
field_data_field_person_image.field_person_image_height,
field_data_field_name.field_name_title,
field_data_field_name.field_name_given,
field_data_field_name.field_name_middle,
field_data_field_name.field_name_family,
field_data_field_address.field_address_country,
field_data_field_address.field_address_administrative_area,
field_data_field_address.field_address_locality,
field_data_field_address.field_address_postal_code,
field_data_field_address.field_address_thoroughfare,
field_data_field_address.field_address_premise,
field_data_field_list_in_directory.field_list_in_directory_value,
field_data_field_organization.field_organization_target_id,
field_data_field_email.field_email_email,
field_data_field_phone.field_phone_value,
field_data_field_orcid.field_orcid_value,
field_data_field_orcid.field_orcid_title
FROM
node
LEFT OUTER JOIN field_data_field_person_department ON node.nid = field_data_field_person_department.entity_id
LEFT OUTER JOIN field_data_field_person_role ON node.nid = field_data_field_person_role.entity_id
LEFT OUTER JOIN field_data_field_person_specialty ON node.nid = field_data_field_person_specialty.entity_id
LEFT OUTER JOIN field_data_field_person_title ON node.nid = field_data_field_person_title.entity_id
LEFT OUTER JOIN field_data_field_person_image ON node.nid = field_data_field_person_image.entity_id
LEFT OUTER JOIN field_data_field_name ON node.nid = field_data_field_name.entity_id
LEFT OUTER JOIN field_data_field_address ON node.nid = field_data_field_address.entity_id
LEFT OUTER JOIN field_data_field_list_in_directory ON node.nid = field_data_field_list_in_directory.entity_id
LEFT OUTER JOIN field_data_field_organization ON node.nid = field_data_field_organization.entity_id
LEFT OUTER JOIN field_data_field_email ON node.nid = field_data_field_email.entity_id
LEFT OUTER JOIN field_data_field_phone ON node.nid = field_data_field_phone.entity_id
LEFT OUTER JOIN field_data_field_orcid ON node.nid = field_data_field_orcid.entity_id
WHERE
node.type = "person" AND
LENGTH(node.title) > 0
